# Generated by Django 4.2.2 on 2023-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=30)),
                ('num_compte', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='login',
            name='num_compte',
        ),
        migrations.RemoveField(
            model_name='login',
            name='prenom',
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='toto', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='toto', max_length=10),
            preserve_default=False,
        ),
    ]
