# Generated by Django 4.2.2 on 2023-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0003_customuser_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nom_compte',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='num_compte',
            field=models.IntegerField(unique=True),
        ),
    ]
