# Generated by Django 4.2.2 on 2023-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0005_remove_account_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='montant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='nom_compte',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='num_compte',
            field=models.IntegerField(),
        ),
    ]
